// Renders a shareable PNG of the Smith-Kerns pressure summary so the
// operator can paste it into WhatsApp / Slack / email. All drawing is
// done with the Canvas 2D API — no extra dependencies, no DOM scraping.
//
// Layout (1200 x 800):
//   ┌─────────────────────────────────────────────────────────────┐
//   │ Ganton G3                                4 May 2026         │
//   │ Dollar spot pressure                                        │
//   │  ┌──────────┐ ┌──────────────┐ ┌──────────────┐             │
//   │  │  42%     │ │  58%  8 May  │ │ 7 images     │             │
//   │  │  Today   │ │  Peak (14d)  │ │ 4.2% disease │             │
//   │  │  Mod.    │ │  High        │ │ avg coverage │             │
//   │  └──────────┘ └──────────────┘ └──────────────┘             │
//   │ [ ─────── 30d history + 14d forecast (dashed) ────── ]      │
//   │ Generated by Dollar Spot Monitor                            │
//   └─────────────────────────────────────────────────────────────┘

import type { PressureScore } from "./airtable";
import type { ForecastPressureRow } from "./forecast-pressure";

export type ShareCardInput = {
  locationName: string;
  /** Optional public URL of the location's own logo. */
  locationLogoUrl?: string | null;
  scores: PressureScore[];
  forecast: ForecastPressureRow[];
  photoCount: number;
  meanDiseasePct: number | null;
  photoDates: string[];
};

const W = 1200;
const H = 800;
const SCALE = 2; // 2400 x 1600 actual pixels for retina

const TEMP = "#d97706";
const RH = "#0284c7";
const PRESSURE = "#374151";
const FORECAST = "#9ca3af";
const PHOTO = "#0284c7";

export async function buildShareCard(input: ShareCardInput): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = W * SCALE;
  canvas.height = H * SCALE;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D not available");
  ctx.scale(SCALE, SCALE);
  ctx.imageSmoothingEnabled = true;

  // Best-effort logo loads — if any fails we still produce a valid card.
  const [striLogo, locationLogo] = await Promise.all([
    loadImage("/stri-logo.png").catch(() => null),
    input.locationLogoUrl
      ? loadImage(input.locationLogoUrl).catch(() => null)
      : Promise.resolve(null),
  ]);

  drawBackground(ctx);
  drawHeader(ctx, input, striLogo, locationLogo);
  drawStatTiles(ctx, input);
  drawChart(ctx, input);
  drawFooter(ctx);

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error("toBlob returned null"))),
      "image/png"
    );
  });
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

function drawBackground(ctx: CanvasRenderingContext2D) {
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, W, H);
}

function drawHeader(
  ctx: CanvasRenderingContext2D,
  input: ShareCardInput,
  striLogo: HTMLImageElement | null,
  locationLogo: HTMLImageElement | null
) {
  // Left side: optional location logo, then location name + subline.
  let textX = 40;
  if (locationLogo && locationLogo.naturalWidth && locationLogo.naturalHeight) {
    const targetH = 56;
    const ratio = locationLogo.naturalWidth / locationLogo.naturalHeight;
    const drawW = targetH * ratio;
    ctx.drawImage(locationLogo, 40, 28, drawW, targetH);
    textX = 40 + drawW + 16;
  }
  ctx.fillStyle = "#1c1917";
  ctx.font = "bold 32px ui-sans-serif, system-ui, -apple-system, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText(input.locationName, textX, 32);
  ctx.fillStyle = "#57534e";
  ctx.font = "16px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText("Dollar spot pressure", textX, 72);

  // Right side: STRI logo (if loaded) above the generated-on date.
  const today = new Date();
  const dateStr = today.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  if (striLogo && striLogo.naturalWidth && striLogo.naturalHeight) {
    const targetH = 56;
    const ratio = striLogo.naturalWidth / striLogo.naturalHeight;
    const drawW = targetH * ratio;
    const x = W - 40 - drawW;
    const y = 24;
    ctx.drawImage(striLogo, x, y, drawW, targetH);
    ctx.fillStyle = "#78716c";
    ctx.font = "13px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "right";
    ctx.fillText(`Generated ${dateStr}`, W - 40, y + targetH + 6);
  } else {
    ctx.textAlign = "right";
    ctx.fillStyle = "#78716c";
    ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
    ctx.fillText(`Generated ${dateStr}`, W - 40, 36);
  }
}

function bandColours(band: string): { bg: string; border: string; fg: string } {
  if (band === "High") return { bg: "#fef2f2", border: "#fca5a5", fg: "#991b1b" };
  if (band === "Moderate")
    return { bg: "#fffbeb", border: "#fcd34d", fg: "#92400e" };
  return { bg: "#f0fdf4", border: "#86efac", fg: "#166534" };
}

function drawStatTiles(ctx: CanvasRenderingContext2D, input: ShareCardInput) {
  const tileY = 110;
  const tileH = 160;
  const gap = 16;
  const totalW = W - 80;
  const tileW = (totalW - gap * 2) / 3;

  const latest = input.scores[input.scores.length - 1];
  const peak = pickPeak(input.forecast);

  drawTile(ctx, 40, tileY, tileW, tileH, {
    bg: latest ? bandColours(latest.risk_band).bg : "#f5f5f4",
    border: latest ? bandColours(latest.risk_band).border : "#d6d3d1",
    label: "Today",
    big: latest
      ? `${(latest.smith_kerns_probability * 100).toFixed(0)}%`
      : "—",
    sub: latest
      ? `${formatShortDate(latest.date)} · ${latest.risk_band}`
      : "no data",
    fg: latest ? bandColours(latest.risk_band).fg : "#44403c",
  });

  drawTile(ctx, 40 + tileW + gap, tileY, tileW, tileH, {
    bg: peak ? bandColours(peak.risk_band).bg : "#f5f5f4",
    border: peak ? bandColours(peak.risk_band).border : "#d6d3d1",
    label: "Peak in next 14 days",
    big: peak ? `${(peak.probability * 100).toFixed(0)}%` : "—",
    sub: peak
      ? `${formatShortDate(peak.date)} · ${peak.risk_band}`
      : "no forecast",
    fg: peak ? bandColours(peak.risk_band).fg : "#44403c",
  });

  drawTile(ctx, 40 + (tileW + gap) * 2, tileY, tileW, tileH, {
    bg: "#f0f9ff",
    border: "#7dd3fc",
    label: "Photos assessed",
    big: String(input.photoCount),
    sub:
      input.meanDiseasePct != null
        ? `${input.meanDiseasePct.toFixed(1)}% mean disease coverage`
        : "no photos yet",
    fg: "#075985",
  });
}

function drawTile(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  spec: { bg: string; border: string; label: string; big: string; sub: string; fg: string }
) {
  // Rounded rect background + 2px border
  roundRect(ctx, x, y, w, h, 12);
  ctx.fillStyle = spec.bg;
  ctx.fill();
  ctx.lineWidth = 2;
  ctx.strokeStyle = spec.border;
  ctx.stroke();

  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillStyle = spec.fg;
  ctx.font = "bold 12px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.label.toUpperCase(), x + 20, y + 18);

  ctx.font = "bold 56px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.big, x + 20, y + 50);

  ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.sub, x + 20, y + h - 30);
}

function drawChart(ctx: CanvasRenderingContext2D, input: ShareCardInput) {
  const top = 300;
  const bottom = 720;
  const left = 60;
  const right = W - 40;
  const chartW = right - left;
  const chartH = bottom - top;

  // X axis: combine scores + forecast (dedup). Each entry has date + value.
  type Pt = {
    date: string;
    value: number;
    isForecast: boolean;
  };
  const points: Pt[] = [];
  for (const s of input.scores) {
    points.push({
      date: s.date,
      value: s.smith_kerns_probability,
      isForecast: false,
    });
  }
  for (const f of input.forecast) {
    points.push({
      date: f.date,
      value: f.smith_kerns_probability,
      isForecast: true,
    });
  }
  if (points.length === 0) {
    ctx.fillStyle = "#a8a29e";
    ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("No pressure data to chart yet", (left + right) / 2, top + chartH / 2);
    return;
  }
  points.sort((a, b) => a.date.localeCompare(b.date));

  const xFor = (i: number) =>
    points.length === 1
      ? left + chartW / 2
      : left + (i / (points.length - 1)) * chartW;
  const yFor = (v: number) => bottom - v * chartH; // domain 0..1

  // Risk-band shading — translucent washes to match the dashboard.
  ctx.fillStyle = "rgba(34, 197, 94, 0.12)"; // green-500 @ 12%
  ctx.fillRect(left, yFor(0.2), chartW, bottom - yFor(0.2));
  ctx.fillStyle = "rgba(245, 158, 11, 0.18)"; // amber-500 @ 18%
  ctx.fillRect(left, yFor(0.3), chartW, yFor(0.2) - yFor(0.3));
  ctx.fillStyle = "rgba(239, 68, 68, 0.22)"; // red-500 @ 22%
  ctx.fillRect(left, top, chartW, yFor(0.3) - top);

  // Y-axis ticks
  ctx.fillStyle = "#78716c";
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "right";
  ctx.textBaseline = "middle";
  for (const v of [0, 0.2, 0.4, 0.6, 0.8, 1.0]) {
    ctx.fillText(`${Math.round(v * 100)}%`, left - 6, yFor(v));
    // gridline
    ctx.beginPath();
    ctx.strokeStyle = "rgba(0,0,0,0.06)";
    ctx.lineWidth = 1;
    ctx.moveTo(left, yFor(v));
    ctx.lineTo(right, yFor(v));
    ctx.stroke();
  }

  // Axis frame
  ctx.strokeStyle = "#e7e5e4";
  ctx.lineWidth = 1;
  ctx.strokeRect(left, top, chartW, chartH);

  // Find boundary index between actual and forecast (last actual)
  let lastActual = -1;
  for (let i = 0; i < points.length; i++) {
    if (!points[i].isForecast) lastActual = i;
  }

  // Actual line (solid)
  if (lastActual >= 0) {
    ctx.beginPath();
    ctx.strokeStyle = PRESSURE;
    ctx.lineWidth = 3;
    ctx.setLineDash([]);
    for (let i = 0; i <= lastActual; i++) {
      const x = xFor(i);
      const y = yFor(points[i].value);
      if (i === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();
  }

  // Forecast line (dashed) — bridge from last actual into forecast
  const forecastStart = lastActual >= 0 ? lastActual : 0;
  if (forecastStart < points.length - 1) {
    ctx.beginPath();
    ctx.strokeStyle = FORECAST;
    ctx.lineWidth = 3;
    ctx.setLineDash([8, 6]);
    for (let i = forecastStart; i < points.length; i++) {
      const x = xFor(i);
      const y = yFor(points[i].value);
      if (i === forecastStart) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();
    ctx.setLineDash([]);
  }

  // Today vertical line
  if (lastActual >= 0) {
    ctx.beginPath();
    ctx.strokeStyle = "#1c1917";
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 4]);
    ctx.moveTo(xFor(lastActual), top);
    ctx.lineTo(xFor(lastActual), bottom);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.fillStyle = "#1c1917";
    ctx.font = "11px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    ctx.fillText("Today", xFor(lastActual) + 4, top + 4);
  }

  // Photo markers (numbered count circles)
  const countByDate = new Map<string, number>();
  for (const d of input.photoDates) {
    countByDate.set(d, (countByDate.get(d) ?? 0) + 1);
  }
  for (let i = 0; i < points.length; i++) {
    const count = countByDate.get(points[i].date);
    if (!count) continue;
    const x = xFor(i);
    const y = top + 18;
    ctx.beginPath();
    ctx.fillStyle = PHOTO;
    ctx.arc(x, y, 11, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = 2;
    ctx.strokeStyle = "#ffffff";
    ctx.stroke();
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 12px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(count > 9 ? "9+" : String(count), x, y + 1);
  }

  // X-axis labels (sparse: first, last, today, plus a few)
  const labelIxs = new Set<number>([0, points.length - 1]);
  if (lastActual >= 0) labelIxs.add(lastActual);
  // add a few intermediate ticks for context
  const stride = Math.max(1, Math.floor(points.length / 6));
  for (let i = 0; i < points.length; i += stride) labelIxs.add(i);

  ctx.fillStyle = "#57534e";
  ctx.font = "11px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  for (const i of labelIxs) {
    ctx.fillText(formatShortDate(points[i].date), xFor(i), bottom + 6);
  }

  // Tiny inline legend
  const legendY = bottom + 28;
  let lx = left;
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.textBaseline = "middle";
  ctx.textAlign = "left";

  // actual
  ctx.beginPath();
  ctx.strokeStyle = PRESSURE;
  ctx.lineWidth = 3;
  ctx.moveTo(lx, legendY);
  ctx.lineTo(lx + 24, legendY);
  ctx.stroke();
  ctx.fillStyle = "#1c1917";
  ctx.fillText("Actual", lx + 30, legendY);
  lx += 100;

  // forecast
  ctx.beginPath();
  ctx.strokeStyle = FORECAST;
  ctx.lineWidth = 3;
  ctx.setLineDash([8, 6]);
  ctx.moveTo(lx, legendY);
  ctx.lineTo(lx + 24, legendY);
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.fillStyle = "#1c1917";
  ctx.fillText("14-day forecast", lx + 30, legendY);
  lx += 160;

  // photo dot
  ctx.beginPath();
  ctx.fillStyle = PHOTO;
  ctx.arc(lx + 8, legendY, 6, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = "#1c1917";
  ctx.fillText("Photo assessed", lx + 22, legendY);
}

function drawFooter(ctx: CanvasRenderingContext2D) {
  ctx.fillStyle = "#a8a29e";
  ctx.font = "11px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "right";
  ctx.textBaseline = "bottom";
  ctx.fillText(
    "Smith-Kerns logistic-regression model · Dollar Spot Monitor · STRI",
    W - 40,
    H - 20
  );
}

function pickPeak(
  forecast: ForecastPressureRow[]
): { date: string; probability: number; risk_band: string } | null {
  if (forecast.length === 0) return null;
  let best = forecast[0];
  for (const f of forecast) {
    if (f.smith_kerns_probability > best.smith_kerns_probability) best = f;
  }
  return {
    date: best.date,
    probability: best.smith_kerns_probability,
    risk_band: best.risk_band,
  };
}

function formatShortDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    timeZone: "UTC",
  });
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

// Try clipboard.write first, fall back to a download.
export async function copyOrDownloadBlob(
  blob: Blob,
  filename: string
): Promise<"clipboard" | "download"> {
  if (
    typeof navigator !== "undefined" &&
    "clipboard" in navigator &&
    typeof (window as Window & { ClipboardItem?: typeof ClipboardItem })
      .ClipboardItem === "function"
  ) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ClipboardItemCtor = (window as any).ClipboardItem;
      await navigator.clipboard.write([
        new ClipboardItemCtor({ "image/png": blob }),
      ]);
      return "clipboard";
    } catch {
      /* fall through */
    }
  }
  // Fallback: download
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return "download";
}
